version: '3.3'

services:
  db:
    image: postgres
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analytics_db
    volumes:
      - ./dbs/postgres-data:/var/lib/postgresql
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 8890:8890
    volumes:
      - .:/project
    command: bash -c "pip install django-extensions && pip install django-filter && pip install django-environ && python ./example_2310/manage.py runserver 0.0.0.0:8890"
    depends_on:
      - db