# Generated by Django 3.1.2 on 2021-10-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0002_auto_20211008_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warriors_app.profession', verbose_name='Профессия'),
        ),
    ]
