# Generated by Django 3.1.2 on 2020-11-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
