# Generated by Django 2.2.6 on 2022-04-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0002_auto_20220427_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Уровень'),
        ),
    ]
