# Generated by Django 2.2.6 on 2022-05-12 06:44

from django.db import migrations, models
import warriors_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0003_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=warriors_app.models.get_upload_path),
        ),
    ]
