# Generated by Django 3.2.10 on 2022-10-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGoods',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warriors_app.goods')),
                ('calory', models.CharField(max_length=100)),
            ],
            bases=('warriors_app.goods',),
        ),
    ]
