# Generated by Django 3.2.10 on 2022-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0007_alter_goods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='new_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
