# Generated by Django 3.2.10 on 2022-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0008_auto_20221010_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, verbose_name='Описание события')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
            ],
        ),
    ]
