# Generated by Django 3.2.10 on 2022-11-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0009_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='title',
            new_name='message',
        ),
    ]
