# Generated by Django 3.2.10 on 2023-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0011_alter_goodsimage_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='damage',
            field=models.IntegerField(default=0, verbose_name='Урон'),
        ),
    ]
